"""Dicionário COMMON_TERMS do protótipo do 1º CGEO (backend/src/services/llm/constants.ts).

Gerado por scripts/extrair_termos_prototipo.py; não editar à mão. Copyright do protótipo:
Exército Brasileiro - Diretoria de Serviço Geográfico, licença MIT (THIRD_PARTY_NOTICES.md).
Usado apenas pela linha de base que reproduz o método do protótipo (agent_estruturado.py);
a solução avaliada não tem dicionário de normalização.
"""

COMMON_TERMS: dict[str, str] = {
    '1cgeo': '1° Centro de Geoinformação',
    '2cgeo': '2° Centro de Geoinformação',
    '3cgeo': '3° Centro de Geoinformação',
    '4cgeo': '4° Centro de Geoinformação',
    '5cgeo': '5° Centro de Geoinformação',
    '1 cgeo': '1° Centro de Geoinformação',
    '2 cgeo': '2° Centro de Geoinformação',
    '3 cgeo': '3° Centro de Geoinformação',
    '4 cgeo': '4° Centro de Geoinformação',
    '5 cgeo': '5° Centro de Geoinformação',
    '1ºcgeo': '1° Centro de Geoinformação',
    '2ºcgeo': '2° Centro de Geoinformação',
    '3ºcgeo': '3° Centro de Geoinformação',
    '4ºcgeo': '4° Centro de Geoinformação',
    '5ºcgeo': '5° Centro de Geoinformação',
    '1º cgeo': '1° Centro de Geoinformação',
    '2º cgeo': '2° Centro de Geoinformação',
    '3º cgeo': '3° Centro de Geoinformação',
    '4º cgeo': '4° Centro de Geoinformação',
    '5º cgeo': '5° Centro de Geoinformação',
    '1ocgeo': '1° Centro de Geoinformação',
    '2ocgeo': '2° Centro de Geoinformação',
    '3ocgeo': '3° Centro de Geoinformação',
    '4ocgeo': '4° Centro de Geoinformação',
    '5ocgeo': '5° Centro de Geoinformação',
    '1o cgeo': '1° Centro de Geoinformação',
    '2o cgeo': '2° Centro de Geoinformação',
    '3o cgeo': '3° Centro de Geoinformação',
    '4o cgeo': '4° Centro de Geoinformação',
    '5o cgeo': '5° Centro de Geoinformação',
    'primeiro cgeo': '1° Centro de Geoinformação',
    'segundo cgeo': '2° Centro de Geoinformação',
    'terceiro cgeo': '3° Centro de Geoinformação',
    'quarto cgeo': '4° Centro de Geoinformação',
    'quinto cgeo': '5° Centro de Geoinformação',
    'primeiro centro': '1° Centro de Geoinformação',
    'segundo centro': '2° Centro de Geoinformação',
    'terceiro centro': '3° Centro de Geoinformação',
    'quarto centro': '4° Centro de Geoinformação',
    'quinto centro': '5° Centro de Geoinformação',
    '1k': '1:1.000',
    '1.k': '1:1.000',
    '1 k': '1:1.000',
    '1.000': '1:1.000',
    '1000': '1:1.000',
    '2k': '1:2.000',
    '2.k': '1:2.000',
    '2 k': '1:2.000',
    '2.000': '1:2.000',
    '2000': '1:2.000',
    '5k': '1:5.000',
    '5.k': '1:5.000',
    '5 k': '1:5.000',
    '5.000': '1:5.000',
    '5000': '1:5.000',
    '10k': '1:10.000',
    '10.k': '1:10.000',
    '10 k': '1:10.000',
    '10.000': '1:10.000',
    '10000': '1:10.000',
    '25k': '1:25.000',
    '25.k': '1:25.000',
    '25 k': '1:25.000',
    '25.000': '1:25.000',
    '25000': '1:25.000',
    '50k': '1:50.000',
    '50.k': '1:50.000',
    '50 k': '1:50.000',
    '50.000': '1:50.000',
    '50000': '1:50.000',
    '100k': '1:100.000',
    '100.k': '1:100.000',
    '100 k': '1:100.000',
    '100.000': '1:100.000',
    '100000': '1:100.000',
    '250k': '1:250.000',
    '250.k': '1:250.000',
    '250 k': '1:250.000',
    '250.000': '1:250.000',
    '250000': '1:250.000',
    'carta topo': 'SCN Carta Topografica Matricial',
    'cartas topo': 'SCN Carta Topografica Matricial',
    'carta topografica': 'SCN Carta Topografica Matricial',
    'carta orto': 'SCN Carta Ortoimagem',
    'cartas orto': 'SCN Carta Ortoimagem',
    'carta ortoimg': 'SCN Carta Ortoimagem',
    'cartas ortoimg': 'SCN Carta Ortoimagem',
    'carta tematica': 'Carta Temática',
    'carta temática': 'Carta Temática',
    'cartas tematicas': 'Carta Temática',
    'cartas temáticas': 'Carta Temática',
    'imagem satélite': 'SCN Carta Ortoimagem',
    'imagem de satélite': 'SCN Carta Ortoimagem',
    'imagem por satélite': 'SCN Carta Ortoimagem',
    'imagem satelite': 'SCN Carta Ortoimagem',
    'mds': 'MDS - RAM',
    'mds ram': 'MDS - RAM',
    'modelo mds': 'Modelo Tridimensional MDS',
    'mdt': 'MDT - RAM',
    'mdt ram': 'MDT - RAM',
    'modelo mdt': 'Modelo Tridimensional MDT',
    'ortoimagem p': 'Ortoimagem banda P',
    'orto p': 'Ortoimagem banda P',
    'ortoimagem p hh': 'Ortoimagem banda P pol HH',
    'orto p hh': 'Ortoimagem banda P pol HH',
    'ortoimagem p hv': 'Ortoimagem banda P pol HV',
    'orto p hv': 'Ortoimagem banda P pol HV',
    'ortoimagem x hh': 'Ortoimagem banda X pol HH',
    'orto x hh': 'Ortoimagem banda X pol HH',
    'orto radar': 'Ortoimagem Radar Colorida',
    'ortoimagem radar': 'Ortoimagem Radar Colorida',
    'orto scn': 'Ortoimagem SCN',
    'carta censipam': 'Cartas CENSIPAM',
    'censipam': 'Cartas CENSIPAM',
    'carta especial': 'SCN Carta Especial Matricial',
    'topo matricial': 'SCN Carta Topografica Matricial',
    'topo vetorial': 'SCN Carta Topografica Vetorial',
    'topo edgv': 'SCN Carta Topografica Vetorial EDGV 3.0',
    'vetorial edgv': 'SCN Carta Topografica Vetorial EDGV 3.0',
    'circ': 'Tematico CIRC',
    'cirp': 'Tematico CIRP',
    'cisc': 'Tematico CISC',
    'cisp': 'Tematico CISP',
    'cmil': 'Tematico CMIL',
    'ctbl': 'Tematico CTBL',
    'ctp': 'Tematico CTP',
    'tematico': 'Cartas Temáticas Não SCN',
    'altura veg': 'Altura da vegetação',
    'altura vegetacao': 'Altura da vegetação',
    'ctm ven': 'CTM Venezuela',
    'venezuela': 'CTM Venezuela',
    'aman': 'AMAN',
    'beca': 'NGA-BECA',
    'nga': 'NGA-BECA',
    'nga beca': 'NGA-BECA',
    'base bahia': 'Base Cartográfica Digital da Bahia',
    'base ba': 'Base Cartográfica Digital da Bahia',
    'base rondonia': 'Base Cartográfica Digital de Rondônia',
    'base ro': 'Base Cartográfica Digital de Rondônia',
    'base amapa': 'Base Cartográfica Digital do Amapá',
    'base ap': 'Base Cartográfica Digital do Amapá',
    'coter': 'COTer Não EDGV',
    'coter nao edgv': 'COTer Não EDGV',
    'base sp': 'Cobertura Aerofotogramétrica do Estado de São Paulo',
    'base sao paulo': 'Cobertura Aerofotogramétrica do Estado de São Paulo',
    'conversao scn': 'Conversão do Mapeamento Sistematico do SCN para Vetorial',
    'copa confederacoes': 'Copa das Confederações',
    'copa 2014': 'Copa do Mundo 2014',
    'copa mundo': 'Copa do Mundo 2014',
    'mapeamento sistematico': 'Mapeamento Sistemático',
    'areas interesse': 'Mapeamento de Áreas de Interesse da Força',
    'interesse forca': 'Mapeamento de Áreas de Interesse da Força',
    'olimpiadas': 'Olimpíadas Rio 2016',
    'olimpiadas 2016': 'Olimpíadas Rio 2016',
    'rio 2016': 'Olimpíadas Rio 2016',
    'ram': 'Radiografia da Amazônia',
    'radiografia amazonia': 'Radiografia da Amazônia',
    'jogos olimpicos': 'Olimpíadas Rio 2016',
    'jogos olímpicos': 'Olimpíadas Rio 2016',
}
